- hosts: localhost
  become: true
  tasks:
  - name: prerequisites
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      state: latest
      update_cache: true
  - name: docker gpg key
    apt_key:
      url: "https://download.docker.com/linux/debian/gpg"
      state: present
  - name: docker apt repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
      state: present
  - name: docker install
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: true
  - name: docker service
    service:
      name: docker
      state: started
  - name: Systemd reload
    systemd:
      daemon_reload: yes
  - name: Install python3 pip
    apt:
     name: python3-pip
     state: latest
     update_cache: true
  - name: Install Docker
    command: pip3 install docker
  - name: Install Requests
    command: pip3 install requests
  - name: Add to group
    user:
     name: coach
     groups:
      - docker
     append: true
     shell: /bin/bash



